// flow-typed signature: b83f65a49eac43c31dd880be0d7e1905
// flow-typed version: <<STUB>>/react-bulma-components_v^1.5.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bulma-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bulma-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bulma-components/dist/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/full/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/jest.config' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/box/box' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/box/box.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/box/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/breadcrumb/breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/breadcrumb/breadcrumb.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/breadcrumb/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/button/button' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/button/button.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/button/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/card' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/card.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/content' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/footer/components/footer-item' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/footer/footer' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/footer/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/header/components/header-icon' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/header/components/header-title' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/header/header' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/header/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/components/image' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/card/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/columns/columns' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/columns/columns.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/columns/components/column' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/columns/constants' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/columns/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/container/container' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/container/container.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/container/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/content/content' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/content/content.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/content/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/dropdown/components/divider' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/dropdown/components/item' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/dropdown/dropdown' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/dropdown/dropdown.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/dropdown/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/footer/footer' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/footer/footer.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/footer/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/checkbox' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/control' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/field/field-body' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/field/field-label' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/field/field' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/field/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/help' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/input' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/label' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/radio' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/select' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/components/textarea' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/form.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/form/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/heading/heading' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/heading/heading.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/heading/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/hero/components/hero-body' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/hero/components/hero-footer' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/hero/components/hero-head' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/hero/hero' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/hero/hero.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/hero/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/icon/icon' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/icon/icon.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/icon/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/image/constants' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/image/image' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/image/image.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/image/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/level/components/level-item' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/level/components/level-side' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/level/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/level/level' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/level/level.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/loader/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/loader/loader' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/loader/loader.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/media/components/media-content' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/media/components/media-item' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/media/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/media/media' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/media/media.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/menu/components/list/components/item' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/menu/components/list/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/menu/components/list/list' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/menu/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/menu/menu' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/menu/menu.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/message/components/body' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/message/components/header' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/message/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/message/message' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/message/message.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/components/card/body' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/components/card/card' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/components/card/foot' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/components/card/head' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/components/card/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/components/card/title' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/components/content' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/modal' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/modal/modal.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/components/brand' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/components/burger' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/components/container' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/components/divider' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/components/dropdown' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/components/item' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/components/link' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/components/menu' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/navbar' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/navbar/navbar.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/notification/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/notification/notification' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/notification/notification.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/pagination/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/pagination/pagination' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/pagination/pagination.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/components/block' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/components/header' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/components/icon' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/components/tabs/components/tab' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/components/tabs/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/components/tabs/tabs' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/panel' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/panel/panel.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/progress/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/progress/progress' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/progress/progress.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/section/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/section/section' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/section/section.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/table/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/table/table' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/table/table.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tabs/components/tab' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tabs/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tabs/tabs' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tabs/tabs.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tag/components/tag-group' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tag/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tag/tag' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tag/tag.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tile/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tile/tile' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/components/tile/tile.story' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/constants' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/index' {
  declare module.exports: any;
}

declare module 'react-bulma-components/lib/services/can-use-dom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bulma-components/dist/index.js' {
  declare module.exports: $Exports<'react-bulma-components/dist/index'>;
}
declare module 'react-bulma-components/full/index.js' {
  declare module.exports: $Exports<'react-bulma-components/full/index'>;
}
declare module 'react-bulma-components/jest.config.js' {
  declare module.exports: $Exports<'react-bulma-components/jest.config'>;
}
declare module 'react-bulma-components/lib/components/box/box.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/box/box'>;
}
declare module 'react-bulma-components/lib/components/box/box.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/box/box.story'>;
}
declare module 'react-bulma-components/lib/components/box/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/box/index'>;
}
declare module 'react-bulma-components/lib/components/breadcrumb/breadcrumb.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/breadcrumb/breadcrumb'>;
}
declare module 'react-bulma-components/lib/components/breadcrumb/breadcrumb.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/breadcrumb/breadcrumb.story'>;
}
declare module 'react-bulma-components/lib/components/breadcrumb/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/breadcrumb/index'>;
}
declare module 'react-bulma-components/lib/components/button/button.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/button/button'>;
}
declare module 'react-bulma-components/lib/components/button/button.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/button/button.story'>;
}
declare module 'react-bulma-components/lib/components/button/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/button/index'>;
}
declare module 'react-bulma-components/lib/components/card/card.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/card'>;
}
declare module 'react-bulma-components/lib/components/card/card.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/card.story'>;
}
declare module 'react-bulma-components/lib/components/card/components/content.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/content'>;
}
declare module 'react-bulma-components/lib/components/card/components/footer/components/footer-item.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/footer/components/footer-item'>;
}
declare module 'react-bulma-components/lib/components/card/components/footer/footer.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/footer/footer'>;
}
declare module 'react-bulma-components/lib/components/card/components/footer/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/footer/index'>;
}
declare module 'react-bulma-components/lib/components/card/components/header/components/header-icon.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/header/components/header-icon'>;
}
declare module 'react-bulma-components/lib/components/card/components/header/components/header-title.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/header/components/header-title'>;
}
declare module 'react-bulma-components/lib/components/card/components/header/header.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/header/header'>;
}
declare module 'react-bulma-components/lib/components/card/components/header/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/header/index'>;
}
declare module 'react-bulma-components/lib/components/card/components/image.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/components/image'>;
}
declare module 'react-bulma-components/lib/components/card/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/card/index'>;
}
declare module 'react-bulma-components/lib/components/columns/columns.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/columns/columns'>;
}
declare module 'react-bulma-components/lib/components/columns/columns.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/columns/columns.story'>;
}
declare module 'react-bulma-components/lib/components/columns/components/column.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/columns/components/column'>;
}
declare module 'react-bulma-components/lib/components/columns/constants.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/columns/constants'>;
}
declare module 'react-bulma-components/lib/components/columns/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/columns/index'>;
}
declare module 'react-bulma-components/lib/components/container/container.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/container/container'>;
}
declare module 'react-bulma-components/lib/components/container/container.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/container/container.story'>;
}
declare module 'react-bulma-components/lib/components/container/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/container/index'>;
}
declare module 'react-bulma-components/lib/components/content/content.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/content/content'>;
}
declare module 'react-bulma-components/lib/components/content/content.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/content/content.story'>;
}
declare module 'react-bulma-components/lib/components/content/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/content/index'>;
}
declare module 'react-bulma-components/lib/components/dropdown/components/divider.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/dropdown/components/divider'>;
}
declare module 'react-bulma-components/lib/components/dropdown/components/item.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/dropdown/components/item'>;
}
declare module 'react-bulma-components/lib/components/dropdown/dropdown.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/dropdown/dropdown'>;
}
declare module 'react-bulma-components/lib/components/dropdown/dropdown.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/dropdown/dropdown.story'>;
}
declare module 'react-bulma-components/lib/components/dropdown/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/dropdown/index'>;
}
declare module 'react-bulma-components/lib/components/footer/footer.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/footer/footer'>;
}
declare module 'react-bulma-components/lib/components/footer/footer.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/footer/footer.story'>;
}
declare module 'react-bulma-components/lib/components/footer/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/footer/index'>;
}
declare module 'react-bulma-components/lib/components/form/components/checkbox.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/checkbox'>;
}
declare module 'react-bulma-components/lib/components/form/components/control.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/control'>;
}
declare module 'react-bulma-components/lib/components/form/components/field/field-body.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/field/field-body'>;
}
declare module 'react-bulma-components/lib/components/form/components/field/field-label.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/field/field-label'>;
}
declare module 'react-bulma-components/lib/components/form/components/field/field.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/field/field'>;
}
declare module 'react-bulma-components/lib/components/form/components/field/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/field/index'>;
}
declare module 'react-bulma-components/lib/components/form/components/help.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/help'>;
}
declare module 'react-bulma-components/lib/components/form/components/input.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/input'>;
}
declare module 'react-bulma-components/lib/components/form/components/label.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/label'>;
}
declare module 'react-bulma-components/lib/components/form/components/radio.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/radio'>;
}
declare module 'react-bulma-components/lib/components/form/components/select.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/select'>;
}
declare module 'react-bulma-components/lib/components/form/components/textarea.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/components/textarea'>;
}
declare module 'react-bulma-components/lib/components/form/form.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/form.story'>;
}
declare module 'react-bulma-components/lib/components/form/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/form/index'>;
}
declare module 'react-bulma-components/lib/components/heading/heading.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/heading/heading'>;
}
declare module 'react-bulma-components/lib/components/heading/heading.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/heading/heading.story'>;
}
declare module 'react-bulma-components/lib/components/heading/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/heading/index'>;
}
declare module 'react-bulma-components/lib/components/hero/components/hero-body.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/hero/components/hero-body'>;
}
declare module 'react-bulma-components/lib/components/hero/components/hero-footer.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/hero/components/hero-footer'>;
}
declare module 'react-bulma-components/lib/components/hero/components/hero-head.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/hero/components/hero-head'>;
}
declare module 'react-bulma-components/lib/components/hero/hero.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/hero/hero'>;
}
declare module 'react-bulma-components/lib/components/hero/hero.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/hero/hero.story'>;
}
declare module 'react-bulma-components/lib/components/hero/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/hero/index'>;
}
declare module 'react-bulma-components/lib/components/icon/icon.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/icon/icon'>;
}
declare module 'react-bulma-components/lib/components/icon/icon.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/icon/icon.story'>;
}
declare module 'react-bulma-components/lib/components/icon/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/icon/index'>;
}
declare module 'react-bulma-components/lib/components/image/constants.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/image/constants'>;
}
declare module 'react-bulma-components/lib/components/image/image.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/image/image'>;
}
declare module 'react-bulma-components/lib/components/image/image.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/image/image.story'>;
}
declare module 'react-bulma-components/lib/components/image/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/image/index'>;
}
declare module 'react-bulma-components/lib/components/level/components/level-item.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/level/components/level-item'>;
}
declare module 'react-bulma-components/lib/components/level/components/level-side.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/level/components/level-side'>;
}
declare module 'react-bulma-components/lib/components/level/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/level/index'>;
}
declare module 'react-bulma-components/lib/components/level/level.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/level/level'>;
}
declare module 'react-bulma-components/lib/components/level/level.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/level/level.story'>;
}
declare module 'react-bulma-components/lib/components/loader/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/loader/index'>;
}
declare module 'react-bulma-components/lib/components/loader/loader.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/loader/loader'>;
}
declare module 'react-bulma-components/lib/components/loader/loader.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/loader/loader.story'>;
}
declare module 'react-bulma-components/lib/components/media/components/media-content.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/media/components/media-content'>;
}
declare module 'react-bulma-components/lib/components/media/components/media-item.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/media/components/media-item'>;
}
declare module 'react-bulma-components/lib/components/media/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/media/index'>;
}
declare module 'react-bulma-components/lib/components/media/media.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/media/media'>;
}
declare module 'react-bulma-components/lib/components/media/media.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/media/media.story'>;
}
declare module 'react-bulma-components/lib/components/menu/components/list/components/item.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/menu/components/list/components/item'>;
}
declare module 'react-bulma-components/lib/components/menu/components/list/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/menu/components/list/index'>;
}
declare module 'react-bulma-components/lib/components/menu/components/list/list.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/menu/components/list/list'>;
}
declare module 'react-bulma-components/lib/components/menu/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/menu/index'>;
}
declare module 'react-bulma-components/lib/components/menu/menu.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/menu/menu'>;
}
declare module 'react-bulma-components/lib/components/menu/menu.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/menu/menu.story'>;
}
declare module 'react-bulma-components/lib/components/message/components/body.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/message/components/body'>;
}
declare module 'react-bulma-components/lib/components/message/components/header.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/message/components/header'>;
}
declare module 'react-bulma-components/lib/components/message/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/message/index'>;
}
declare module 'react-bulma-components/lib/components/message/message.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/message/message'>;
}
declare module 'react-bulma-components/lib/components/message/message.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/message/message.story'>;
}
declare module 'react-bulma-components/lib/components/modal/components/card/body.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/components/card/body'>;
}
declare module 'react-bulma-components/lib/components/modal/components/card/card.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/components/card/card'>;
}
declare module 'react-bulma-components/lib/components/modal/components/card/foot.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/components/card/foot'>;
}
declare module 'react-bulma-components/lib/components/modal/components/card/head.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/components/card/head'>;
}
declare module 'react-bulma-components/lib/components/modal/components/card/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/components/card/index'>;
}
declare module 'react-bulma-components/lib/components/modal/components/card/title.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/components/card/title'>;
}
declare module 'react-bulma-components/lib/components/modal/components/content.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/components/content'>;
}
declare module 'react-bulma-components/lib/components/modal/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/index'>;
}
declare module 'react-bulma-components/lib/components/modal/modal.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/modal'>;
}
declare module 'react-bulma-components/lib/components/modal/modal.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/modal/modal.story'>;
}
declare module 'react-bulma-components/lib/components/navbar/components/brand.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/components/brand'>;
}
declare module 'react-bulma-components/lib/components/navbar/components/burger.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/components/burger'>;
}
declare module 'react-bulma-components/lib/components/navbar/components/container.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/components/container'>;
}
declare module 'react-bulma-components/lib/components/navbar/components/divider.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/components/divider'>;
}
declare module 'react-bulma-components/lib/components/navbar/components/dropdown.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/components/dropdown'>;
}
declare module 'react-bulma-components/lib/components/navbar/components/item.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/components/item'>;
}
declare module 'react-bulma-components/lib/components/navbar/components/link.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/components/link'>;
}
declare module 'react-bulma-components/lib/components/navbar/components/menu.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/components/menu'>;
}
declare module 'react-bulma-components/lib/components/navbar/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/index'>;
}
declare module 'react-bulma-components/lib/components/navbar/navbar.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/navbar'>;
}
declare module 'react-bulma-components/lib/components/navbar/navbar.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/navbar/navbar.story'>;
}
declare module 'react-bulma-components/lib/components/notification/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/notification/index'>;
}
declare module 'react-bulma-components/lib/components/notification/notification.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/notification/notification'>;
}
declare module 'react-bulma-components/lib/components/notification/notification.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/notification/notification.story'>;
}
declare module 'react-bulma-components/lib/components/pagination/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/pagination/index'>;
}
declare module 'react-bulma-components/lib/components/pagination/pagination.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/pagination/pagination'>;
}
declare module 'react-bulma-components/lib/components/pagination/pagination.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/pagination/pagination.story'>;
}
declare module 'react-bulma-components/lib/components/panel/components/block.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/components/block'>;
}
declare module 'react-bulma-components/lib/components/panel/components/header.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/components/header'>;
}
declare module 'react-bulma-components/lib/components/panel/components/icon.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/components/icon'>;
}
declare module 'react-bulma-components/lib/components/panel/components/tabs/components/tab.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/components/tabs/components/tab'>;
}
declare module 'react-bulma-components/lib/components/panel/components/tabs/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/components/tabs/index'>;
}
declare module 'react-bulma-components/lib/components/panel/components/tabs/tabs.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/components/tabs/tabs'>;
}
declare module 'react-bulma-components/lib/components/panel/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/index'>;
}
declare module 'react-bulma-components/lib/components/panel/panel.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/panel'>;
}
declare module 'react-bulma-components/lib/components/panel/panel.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/panel/panel.story'>;
}
declare module 'react-bulma-components/lib/components/progress/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/progress/index'>;
}
declare module 'react-bulma-components/lib/components/progress/progress.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/progress/progress'>;
}
declare module 'react-bulma-components/lib/components/progress/progress.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/progress/progress.story'>;
}
declare module 'react-bulma-components/lib/components/section/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/section/index'>;
}
declare module 'react-bulma-components/lib/components/section/section.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/section/section'>;
}
declare module 'react-bulma-components/lib/components/section/section.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/section/section.story'>;
}
declare module 'react-bulma-components/lib/components/table/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/table/index'>;
}
declare module 'react-bulma-components/lib/components/table/table.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/table/table'>;
}
declare module 'react-bulma-components/lib/components/table/table.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/table/table.story'>;
}
declare module 'react-bulma-components/lib/components/tabs/components/tab.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tabs/components/tab'>;
}
declare module 'react-bulma-components/lib/components/tabs/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tabs/index'>;
}
declare module 'react-bulma-components/lib/components/tabs/tabs.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tabs/tabs'>;
}
declare module 'react-bulma-components/lib/components/tabs/tabs.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tabs/tabs.story'>;
}
declare module 'react-bulma-components/lib/components/tag/components/tag-group.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tag/components/tag-group'>;
}
declare module 'react-bulma-components/lib/components/tag/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tag/index'>;
}
declare module 'react-bulma-components/lib/components/tag/tag.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tag/tag'>;
}
declare module 'react-bulma-components/lib/components/tag/tag.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tag/tag.story'>;
}
declare module 'react-bulma-components/lib/components/tile/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tile/index'>;
}
declare module 'react-bulma-components/lib/components/tile/tile.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tile/tile'>;
}
declare module 'react-bulma-components/lib/components/tile/tile.story.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/components/tile/tile.story'>;
}
declare module 'react-bulma-components/lib/constants.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/constants'>;
}
declare module 'react-bulma-components/lib/index.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/index'>;
}
declare module 'react-bulma-components/lib/services/can-use-dom.js' {
  declare module.exports: $Exports<'react-bulma-components/lib/services/can-use-dom'>;
}
